@echo off
cls
Title 正在重编译design_pattern.......
@echo 即将重编译工程项目design_pattern.sln,请稍等.....
if exist %cd%\build.log del %cd%\build.log
@call "%VS120COMNTOOLS%\vsvars32.bat"
@devenv design_pattern.sln /ReBuild "Release|Win32" /out %cd%\build.log
@echo 重编译项目完成! 请按住任意键退出....
@pause>nul & exit
